name: Build


on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.KEYPASSWORD }}" --output ./android/app/keystore/upload-keystore.jks ./android/app/keystore/upload-keystore.jks.gpg
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: 'pubspec.yaml'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk
        env: 
          storePassword: ${{ secrets.STOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}
          keyAlias: 'upload'
          storeFile: './keystore/upload-keystore.jks'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Rename apk
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/${{ github.ref_name }}-release.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/app/outputs/flutter-apk/app-release.apk
