name: Build


on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.KEYPASSWORD }}" --output ./android/app/keystore/upload-keystore.jks ./android/app/keystore/upload-keystore.jks.gpg
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: 'pubspec.yaml'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk
        env: 
          storePassword: ${{ secrets.STOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}
          keyAlias: 'upload'
          storeFile: './keystore/upload-keystore.jks'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: build.apk
          path: build/app/outputs/flutter-apk/*.apk

      - name: Create Release 
        if: startsWith(github.ref, 'refs/tags/') 
        uses: actions/create-release@v1 
        id: create_release 
        with: 
          draft: false 
          prerelease: false 
          release_name: ${{ github.ref }} 
          tag_name: ${{ github.ref }} 
          body_path: CHANGELOG.md 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release 
        if: startsWith(github.ref, 'refs/tags/') 
        uses: actions/upload-release-asset@v1 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: build/app/outputs/flutter-apk/*.apk
          asset_name: ${{ github.ref }}-release.apk
          asset_content_type: application/vnd.android.package-archive
